bot: 
    api_key: API_KEY
    channel_id: 
    admins: 
files:
    users_content: content
    users_list: users.csv
messages:
    start_message: "*Это предложка канала-анала.*\nОтправь сюда свой мем в виде картинки, видео или гифки\n\nДругой контент не поддерживается"
    send_message: "*Ваш мем успешно отправлен*\n_Ожидай публикации в канале-анале_"
    content_caption: "*Думайте* Подписаться"



